# SciPy
Scipy是一个用于数学、科学、工程领域的常用软件包，可以处理插值、积分、优化、图像处理、常微分方程数值解的求解、信号处理等问题。它用于有效计算Numpy矩阵，使Numpy和Scipy协同工作，高效解决问题。

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

## 线性代数

In [2]:
from scipy import linalg

In [3]:
# Compute the determinant of a matrix
linalg.det(A)

2.999999999999997

* Lu矩阵分解
* 分解公式:

    A = P L U

* 注： P 置换矩阵, L 下三角矩阵，U 上三角矩阵。

In [4]:
P, L, U = linalg.lu(A)

In [5]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [6]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [7]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [8]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

### 特征值和特征向量

In [9]:
EW, EV = linalg.eig(A)

In [10]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [11]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

### 求解

In [12]:
v = np.array([[2],[3],[5]])

In [13]:
v

array([[2],
       [3],
       [5]])

In [14]:
s = linalg.solve(A,v)

In [15]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## 稀疏线性代数

In [16]:
from scipy import sparse

In [17]:
A = sparse.lil_matrix((1000, 1000))

In [18]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [19]:
A[0,:100] = np.random.rand(100)

In [20]:
A[1,100:200] = A[0,:100]

In [21]:
A.setdiag(np.random.rand(1000))

In [22]:
A

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

### 线性代数和稀疏矩阵

In [23]:
from scipy.sparse import linalg

In [24]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [25]:
A = A.tocsr()

In [26]:
b = np.random.rand(1000)

In [27]:
linalg.spsolve(A, b)

array([ -5.43322215e+00,  -5.25155681e+02,   3.77213070e-01,
         1.76865170e-02,   6.79282548e-01,   5.52120614e+00,
         1.09521043e+00,   2.80154789e-01,   1.03415901e+00,
         4.63653111e-01,   1.94301295e+01,   1.70158063e-02,
         9.67355099e-01,   5.04483380e-01,   5.17833886e+00,
         7.21686718e-01,   6.86160708e+00,   8.46182502e-01,
         8.40376222e-01,   3.11455305e-01,   6.42971230e-01,
         4.74912822e-01,   7.74590122e-01,   3.29225665e-01,
         6.53086387e-02,   5.19117992e+00,   2.88541014e+00,
         1.00695532e+00,   6.89631250e+00,   1.75718214e+00,
         4.96385885e-01,   1.09086886e-01,   1.24368702e+00,
         3.20795630e-02,   5.21413461e-01,   2.53691279e+00,
         3.62471045e+01,   2.08852945e-01,   1.68154466e+00,
         8.27681269e-01,   1.48348736e-01,   6.87578329e-01,
         1.13811378e+00,   5.39545260e+00,   5.71235278e-02,
         1.43974639e+00,   9.25593439e-01,   4.66402183e+00,
         2.16523879e+00,