# numpy
NumPy系统是Python的一种开源的数值计算扩展。这种工具可用来存储和处理大型矩阵，比Python自身的嵌套列表（nested list structure)结构要高效的多（该结构也可以用来表示矩阵（matrix））。

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [13]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [15]:
np.random.rand(2)

array([ 0.18944409,  0.08081154])

In [16]:
np.random.rand(5,5)

array([[ 0.67303973,  0.78904241,  0.41007492,  0.40426551,  0.06869684],
       [ 0.11582709,  0.65169062,  0.26821995,  0.15366724,  0.9493624 ],
       [ 0.96461419,  0.3349883 ,  0.4384631 ,  0.89335181,  0.84420607],
       [ 0.01962937,  0.26170276,  0.28448581,  0.29626416,  0.47590042],
       [ 0.0034343 ,  0.31634831,  0.56206331,  0.62817742,  0.64996062]])

In [17]:
np.random.randn(2)

array([ 1.06438013, -0.29386152])

In [18]:
np.random.randn(5,5)

array([[ 0.6242635 ,  0.38757453,  0.79138683, -0.53792551, -0.36395353],
       [ 0.68138504,  0.99590248, -0.01515013,  0.74314576,  0.25946853],
       [ 0.51662345, -1.02198563,  0.5527723 ,  0.10165288, -0.28573892],
       [ 1.12029021,  0.39578477,  1.21243404, -1.01148339,  0.6771479 ],
       [-0.17344695, -0.52481166,  1.33401842, -1.5937079 ,  0.41780173]])

In [19]:
np.random.randint(1,100)

6

In [20]:
np.random.randint(1,100,10)

array([45, 62, 50, 80,  2, 34, 73, 74, 99,  9])

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([40,  9, 20, 33, 13, 21, 30, 40, 44,  3])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr

array([40,  9, 20, 33, 13, 21, 30, 40, 44,  3])

In [26]:
ranarr.max()

44

In [27]:
ranarr.argmax()

8

In [28]:
ranarr.min()

3

In [29]:
ranarr.argmin()

9

In [30]:
# Vector
arr.shape

(25,)

In [31]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [32]:
arr.reshape(1,25).shape

(1, 25)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

In [35]:
arr.dtype

dtype('int32')